version: '2.1'
orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
jobs:
  build:
    machine: true
    steps:
      - checkout
      - checkov/install
      - bridgecrew/scan:
          api-key-variable: BC_API_KEY
          directory: .
          prisma-api-url: https://api.prismacloud.io
workflows: null
